### ISSUE TITLE
Help with unknown version

### ISSUE THREAD

**Issue by jasonkarns** [zeke/npm-cdn#8]
At present, a version number is *required* to get an npm package. Which means, if I want to get the latest version, I have to go over to npmjs, find the module, and look up what the latest version is.

It would be nice if `https://npm-cdn.herokuapp.com/axe-core` gave a list of published versions (especially as links) so I didn't have to leave npm-cdn to find that info on npmjs.

**Comment by zeke** [comment]
From the README:

> If you request a package without specifying a version, you'll be redirected to the index for the latest version of the package:

> /lodash redirects to /lodash@2.4.1

See https://npm-cdn.herokuapp.com/axe-core

**Comment by jasonkarns** [comment]
Hmm, sorry about that. I got an error with that url earlier. Thanks!

**Comment by jasonkarns** [comment]
Oh, I remember why: I tried `https://npm-cdn.herokuapp.com/axe-core/axe.js`, which gives an error.
